server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    dbType: mysql
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/zhpt?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
