server:
  port: 8080                              #云平台端口，改用独立tomcat后，该配置无效
  servlet:
    context-path: /
spring:
  jmx:
    default-domain: bendi
  application:
    name: bendi
  datasource:
    dbType: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver #下面这行是配置数据库，这里一定要检查
    url: jdbc:mysql://localhost:3306/jane_learn?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&userSSL=true
    username: root
    password: password